export const AppActions = {
    LOAD_PROFILE_START: 'LOAD_PROFILE_START',
    LOAD_PROFILE_COMPLETED: 'LOAD_PROFILE_COMPLETED',
    LOAD_PROFILE_FAILED: 'LOAD_PROFILE_FAILED',

    LOAD_CONTACTS_START: 'LOAD_CONTACTS_START',
    LOAD_CONTACTS_COMPLETED: 'LOAD_CONTACTS_COMPLETED',
    LOAD_CONTACTS_FAILED: 'LOAD_CONTACTS_FAILED',

    SAY_HELLO: 'SAY_HELLO'
}